import Link from 'next/link';
import { Shell } from '../../../components/Shell';
import { createClient } from '../../../lib/supabase/server';

export default async function AdminJobsPage() {
  const supabase = await createClient();
  const [jobsResult, importsResult, applicationsResult] = await Promise.all([
    supabase.from('jobs').select('id, title, company, location, source, created_at').order('created_at', { ascending: false }).limit(50),
    supabase.from('instagram_job_imports').select('id, caption, status, posted_at, created_at').order('created_at', { ascending: false }).limit(10),
    supabase.from('applications').select('id', { count: 'exact', head: true }),
  ]);
  const jobs = jobsResult.data ?? [];
  const imports = importsResult.data ?? [];
  const pending = imports.filter(item => item.status === 'pending').length;
  const sources = [...new Set(jobs.map(job => job.source || 'Manual'))];
  return <Shell admin><div className="admin-pro-page jobs-operations-page"><header className="admin-hero"><div><span className="admin-eyebrow">JOB OPERATIONS</span><h1>Jobs</h1><p>Manage and monitor job postings, applications, and job scrapers.</p></div><div className="admin-hero-actions"><Link className="admin-secondary-action" href="/admin/instagram">Instagram imports {pending ? `(${pending})` : ''}</Link><Link className="admin-primary-action" href="/jobs">Open public jobs</Link></div></header><section className="job-kpi-grid"><div><span>▣</span><small>Total Jobs</small><strong>{jobs.length.toLocaleString('en-IN')}</strong><em>Published records</em></div><div><span>◉</span><small>Active Jobs</small><strong>{jobs.length.toLocaleString('en-IN')}</strong><em>Visible to users</em></div><div><span>▤</span><small>Applications</small><strong>{(applicationsResult.count ?? 0).toLocaleString('en-IN')}</strong><em>Tracked applications</em></div><div><span>◎</span><small>Job Scrapers</small><strong>{sources.length}</strong><em>{pending} pending review</em></div></section><div className="admin-grid-pro admin-jobs-grid"><section className="admin-panel-pro"><div className="panel-heading"><div><small>PUBLISHED JOBS</small><h2>{jobs.length ? `${jobs.length} recent jobs` : 'No published jobs'}</h2></div><Link href="/admin/instagram" className="panel-link">Review imports →</Link></div>{jobs.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Company</th><th>Location</th><th>Type</th><th>Posted</th><th>Status</th></tr></thead><tbody>{jobs.map(job => <tr key={job.id}><td><Link href={`/jobs/${job.id}`}>{job.title}</Link><small className="admin-table-subtitle">{job.company}</small></td><td>{job.company}</td><td>{job.location || '—'}</td><td>Full-time</td><td>{new Date(job.created_at).toLocaleDateString('en-IN')}</td><td><span className="status-chip">Active</span></td></tr>)}</tbody></table></div> : <div className="admin-empty">No jobs have been published. Import a source to begin review.</div>}</section><section className="admin-panel-pro"><div className="panel-heading"><div><small>INGESTION PIPELINE</small><h2>Source monitor</h2></div></div><div className="pipeline-list"><span>1. Import source content</span><span>2. Extract job details</span><span>3. Duplicate check</span><span>4. Admin review</span><span>5. Publish to users</span></div><div className="scraper-source-summary"><strong>{sources.length}</strong><span>active job source{sources.length === 1 ? '' : 's'}</span><small>{pending} Instagram import{pending === 1 ? '' : 's'} waiting for review</small></div><Link className="admin-primary-action" href="/admin/instagram">Open Instagram scraper →</Link></section></div></div></Shell>;
}
