import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Shell } from '../../../../../components/Shell';
import { createClient } from '../../../../../lib/supabase/server';

export default async function JobApplicationsPage({ params }: { params: Promise<{ jobId: string }> }) {
  const { jobId } = await params; const supabase = await createClient();
  const [{ data: job }, { data: applications }] = await Promise.all([supabase.from('jobs').select('id,title,company').eq('id', jobId).maybeSingle(), supabase.from('applications').select('id,applicant_name,applicant_email,status,created_at').eq('job_id', jobId).order('created_at', { ascending: false })]);
  if (!job) notFound(); const rows = applications ?? [];
  return <Shell admin><div className="admin-pro-page jobs-management-page"><div className="job-details-breadcrumb"><Link href={`/admin/jobs/${job.id}`}>Job Details</Link><span>›</span><span>Applications</span></div><header className="admin-hero"><div><span className="admin-eyebrow">JOB APPLICATIONS</span><h1>Applications for {job.title}</h1><p>{job.company} · {rows.length} total applications</p></div></header><div className="jobs-management-kpis"><div><small>Total Applications</small><strong>{rows.length}</strong></div><div><small>Viewed</small><strong>{rows.filter(row => row.status === 'screening').length}</strong></div><div><small>Shortlisted</small><strong>{rows.filter(row => row.status === 'interview' || row.status === 'offer').length}</strong></div><div><small>Rejected</small><strong>{rows.filter(row => row.status === 'rejected').length}</strong></div><div><small>Pending</small><strong>{rows.filter(row => row.status === 'saved' || row.status === 'applied').length}</strong></div></div><section className="admin-panel-pro applications-panel"><div className="jobs-list-toolbar"><nav><Link className="active" href={`/admin/jobs/${job.id}/applications`}>All ({rows.length})</Link><Link href={`/admin/jobs/${job.id}/applications?status=applied`}>Applied</Link><Link href={`/admin/jobs/${job.id}/applications?status=interview`}>Shortlisted</Link><Link href={`/admin/jobs/${job.id}/applications?status=rejected`}>Rejected</Link></nav></div>{rows.length ? <div className="jobs-management-table-wrap"><table className="jobs-management-table"><thead><tr><th>Applicant</th><th>Email</th><th>Applied On</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><strong>{row.applicant_name || 'Applicant'}</strong></td><td>{row.applicant_email || 'Not provided'}</td><td>{new Date(row.created_at).toLocaleDateString('en-IN')}</td><td><span className="job-active-pill">{row.status}</span></td><td><Link className="table-action" href={`/admin/applicants/${row.id}`}>View</Link></td></tr>)}</tbody></table></div> : <div className="admin-empty">No applications have been submitted for this job.</div>}</section></div></Shell>;
}
