'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { createClient } from '../lib/supabase/client';
import { LogoutButton } from './LogoutButton';

type Account = { name: string; email: string; role: string; avatar: string | null };

export function AccountMenu() {
  const [account, setAccount] = useState<Account | null>(null);
  const [open, setOpen] = useState(false);
  const [uploading, setUploading] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const supabase = createClient(); let active = true; async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user || !active) return; const { data: profile } = await supabase.from('profiles').select('full_name,role,avatar_url').eq('id', user.id).maybeSingle(); const adminEmails = ['admin@softwarechinnodu.com', 'vardhanmudra12@gmail.com']; const isAdmin = profile?.role === 'admin' || adminEmails.includes((user.email || '').toLowerCase()); const email = (user.email || '').toLowerCase(); const profileName = profile?.full_name && profile.full_name.toLowerCase() !== email ? profile.full_name : null; const metadataName = typeof user.user_metadata?.full_name === 'string' && user.user_metadata.full_name.toLowerCase() !== email ? user.user_metadata.full_name : null; setAccount({ name: isAdmin ? (profileName || metadataName || 'Admin') : (profileName || metadataName || user.email?.split('@')[0] || 'User'), email: user.email || '', role: isAdmin ? 'Super Admin' : 'Active Learner', avatar: profile?.avatar_url || user.user_metadata?.avatar_url || null }); } load(); return () => { active = false; }; }, []);
  useEffect(() => { if (!open) return; function onDoc(e: MouseEvent) { if (menuRef.current && !menuRef.current.contains(e.target as Node)) setOpen(false); } function onKey(e: KeyboardEvent) { if (e.key === 'Escape') setOpen(false); } document.addEventListener('mousedown', onDoc); document.addEventListener('keydown', onKey); return () => { document.removeEventListener('mousedown', onDoc); document.removeEventListener('keydown', onKey); }; }, [open]);
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file || !account) return; if (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024) { alert('Please choose an image smaller than 5 MB.'); return; } setUploading(true); const supabase = createClient(); try { const { data: { user }, error: userError } = await supabase.auth.getUser(); if (userError || !user) throw userError || new Error('You must be signed in to upload a profile photo.'); const extension = file.name.split('.').pop()?.toLowerCase() || 'jpg'; const path = `${user.id}/avatar-${Date.now()}.${extension}`; const { error: uploadError } = await supabase.storage.from('avatars').upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) throw uploadError; const { data } = supabase.storage.from('avatars').getPublicUrl(path); const { error: profileError } = await supabase.from('profiles').update({ avatar_url: data.publicUrl }).eq('id', user.id); if (profileError) throw profileError; setAccount({ ...account, avatar: data.publicUrl }); } catch (error) { alert(error instanceof Error ? error.message : 'Could not update your profile photo.'); } finally { setUploading(false); } }
  async function resetPassword() { if (!account?.email) return; const { error } = await createClient().auth.resetPasswordForEmail(account.email, { redirectTo: `${window.location.origin}/reset-password` }); if (error) alert(error.message); else alert('Password reset instructions were sent to your email.'); }
  const initials = account?.name?.slice(0, 1).toUpperCase() || 'U';
  return <div className="account-menu" ref={menuRef}><button className={`account-trigger${open ? ' open' : ''}`} type="button" aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen(!open)}><span className="account-avatar">{account?.avatar ? <img src={account.avatar} alt="Profile"/> : initials}</span><span className="account-copy"><b>{account?.name || 'Loading...'}</b><small>{account?.role || 'Account'}</small></span><span className="account-chevron"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><polyline points="5 8 12 15 19 8"/></svg></span></button>{open && <div className="account-dropdown" role="menu"><button type="button" role="menuitem" onClick={() => inputRef.current?.click()}>{uploading ? 'Uploading...' : 'Upload profile photo'}</button><Link href="/settings" role="menuitem">Profile</Link><button type="button" role="menuitem" onClick={resetPassword}>Reset password</button><Link href="/dashboard" role="menuitem">Dashboard</Link><LogoutButton /></div>}<input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} hidden/></div>;
}
