'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { LogoutButton } from './LogoutButton';
import { NotificationButton } from './NotificationButton';
import { MessageButton } from './MessageButton';
import { AccountMenu } from './AccountMenu';

const userNav = [['Dashboard', '/dashboard'], ['Jobs', '/jobs'], ['Voice Talk Zone', '/voice-talk-zone'], ['Resume Builder', '/resume-builder'], ['Mock Tests', '/mock-tests'], ['AI Tools', '/ai-tools'], ['Learning', '/learning'], ['Applications', '/applications'], ['Saved Jobs', '/saved-jobs'], ['Career Insights', '/career-insights'], ['Settings', '/settings']];
const adminNav = [['⌂', 'Overview', '/admin/dashboard'], ['♙', 'Users', '/admin/users'], ['▣', 'Jobs & Scrapers', '/admin/jobs'], ['•', 'Jobs', '/admin/jobs'], ['•', 'Scrapers', '/admin/instagram'], ['•', 'Applications', '/admin/applications'], ['✦', 'AI Services', '/admin/ai-services'], ['▧', 'Resume Builder', '/resume-builder'], ['✓', 'Mock Tests', '/mock-tests'], ['◇', 'Learning Content', '/learning'], ['♧', 'Voice Talk Zone', '/voice-talk-zone'], ['✧', 'AI Tools', '/ai-tools'], ['▥', 'Analytics', '/admin/analytics'], ['⌁', 'System Health', '/admin/health'], ['⚙', 'Settings', '/settings']];
const publicNav = [['Home', '/homepage'], ...userNav.slice(1)];

export function Shell({ children, admin = false, publicMode = false }: { children: React.ReactNode; admin?: boolean; publicMode?: boolean }) {
  const pathname = usePathname();
  const items = publicMode ? publicNav : admin ? adminNav : userNav;
  return <div className={`shell ${publicMode ? 'public-shell' : ''} ${admin ? 'admin-shell' : ''}`}><aside className="side"><Link href={publicMode ? '/homepage' : admin ? '/admin/dashboard' : '/dashboard'} className="brand"><img className="brand-mark" src="/softwarechinnodu-mark.png" alt="SoftwareChinnodu logo"/><strong>SoftwareChinnodu</strong><small>{admin ? 'Admin Panel' : 'AI Career Partner'}</small></Link><nav className="nav">{items.map((item, index) => { const [icon, label, href] = admin ? item : ['•', item[0], item[1]]; const sub = admin && ['Jobs', 'Scrapers', 'Applications'].includes(label); const active = pathname === href || (label === 'Jobs & Scrapers' && pathname.startsWith('/admin/jobs')); return <Link key={`${href}-${index}`} href={href} className={`${active ? 'active' : ''} ${sub ? 'nav-subitem' : ''} ${label === 'Jobs & Scrapers' ? 'nav-group' : ''}`}><span>{icon}</span>{label}{label === 'Jobs & Scrapers' && <b>⌄</b>}</Link>; })}</nav>{admin ? <div className="admin-platform-status"><strong><i/>Platform Status</strong><small>All systems operational</small>{['Database', 'AI Services', 'Job Scrapers', 'Storage', 'Authentication'].map(item => <span key={item}><b>✓</b>{item}</span>)}</div> : <div className="side-bottom">Upgrade to Premium<br/><span>Unlock advanced AI tools, unlimited mock tests, priority support &amp; more.</span>{publicMode ? <Link className="button button-block" href="/register">Register Now</Link> : <LogoutButton />}</div>}</aside><main className="main"><header className="top"><span className="mobile-menu">☰</span><div className="search">Search users, jobs, applications, logs... <span style={{ marginLeft: 'auto' }}>⌕</span></div><div className="top-right">{publicMode ? <><Link className="login-link" href="/login">Login</Link><Link className="login-link public-register" href="/register">Register</Link></> : <><NotificationButton /><MessageButton /><AccountMenu /></>}</div></header>{children}</main></div>;
}
