import Link from 'next/link';
import { Shell } from '../../../components/Shell';
import { createClient } from '../../../lib/supabase/server';

export default async function AdminDashboard() {
  const supabase = await createClient();
  const [users, jobs, applications, tests, learning, activity, scraperJobs] = await Promise.all([
    supabase.from('profiles').select('*', { count: 'exact', head: true }),
    supabase.from('jobs').select('*', { count: 'exact', head: true }),
    supabase.from('applications').select('*', { count: 'exact', head: true }),
    supabase.from('mock_tests').select('*', { count: 'exact', head: true }),
    supabase.from('learning_progress').select('*', { count: 'exact', head: true }),
    supabase.from('profiles').select('id, full_name, created_at').order('created_at', { ascending: false }).limit(5),
    supabase.from('jobs').select('source, created_at').order('created_at', { ascending: false }),
  ]);
  const sourceNames = ['LinkedIn', 'Indeed', 'Naukri', 'Glassdoor', 'Company Sites', 'Instagram Posts'];
  const sourceRows = sourceNames.map(source => {
    const rows = (scraperJobs.data ?? []).filter(job => (job.source || '').toLowerCase().includes(source.toLowerCase().replace('company sites', 'company')));
    const today = rows.filter(job => new Date(job.created_at).toDateString() === new Date().toDateString()).length;
    return { source, today, total: rows.length };
  });
  const metrics = [['Total Users', users.count ?? 0, 'Registered profiles', 'purple', '♙'], ['Active Users', users.count ?? 0, 'Profiles on platform', 'blue', '♙'], ['Total Jobs', jobs.count ?? 0, 'Published opportunities', 'indigo', '▣'], ['Applications', applications.count ?? 0, 'Applications tracked', 'orange', '¤'], ['Tests Taken', tests.count ?? 0, 'Completed assessments', 'pink', '✓'], ['Learning Enrollments', learning.count ?? 0, 'Active enrollments', 'violet', '◆']] as const;
  const databaseReady = !users.error && !jobs.error && !applications.error;
  const healthItems = [['Web Application', 'Operational'], ['Database (Supabase)', databaseReady ? 'Operational' : 'Unavailable'], ['AI Services (OpenAI)', 'Not configured'], ['Job Scrapers', 'Not configured'], ['Storage (CDN)', 'Not configured'], ['Email Service', 'Not configured']];
  return <Shell admin><div className="admin-pro-page admin-reference-page">
    <header className="admin-reference-header"><div><h1>Admin Dashboard</h1><p>Manage and monitor your AI Career Intelligence Platform</p></div><time>▣ &nbsp; {new Date().toLocaleDateString('en-IN', { dateStyle: 'medium' })} &nbsp; | &nbsp; {new Date().toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit' })}</time></header>
    <section className="admin-reference-metrics">{metrics.map(([label, value, note, color, icon]) => <article className={`reference-metric ${color}`} key={label}><span>{icon}</span><div><small>{label}</small><strong>{Number(value).toLocaleString('en-IN')}</strong><p>{note}</p></div></article>)}</section>
    <section className="admin-reference-grid">
      <article className="reference-panel growth-reference"><header><div><h2>Platform Growth</h2><div className="reference-legend"><i className="legend-users"/>Users <i className="legend-jobs"/>Jobs <i className="legend-apps"/>Applications <i className="legend-tests"/>Tests</div></div><select defaultValue="30"><option value="30">Last 30 Days</option></select></header><div className="line-chart"><div className="chart-y-labels"><span>50k</span><span>40k</span><span>30k</span><span>20k</span><span>10k</span><span>0</span></div><svg viewBox="0 0 600 150" preserveAspectRatio="none" aria-label="Platform growth chart"><path className="chart-area" d="M0 120 L55 105 L110 91 L165 82 L220 70 L275 61 L330 45 L385 43 L440 30 L495 22 L550 12 L600 2 L600 150 L0 150 Z"/><polyline className="chart-line jobs-line" points="0,120 55,105 110,91 165,82 220,70 275,61 330,45 385,43 440,30 495,22 550,12 600,2"/><polyline className="chart-line users-line" points="0,132 55,121 110,113 165,106 220,98 275,90 330,80 385,72 440,63 495,54 550,45 600,35"/><polyline className="chart-line apps-line" points="0,141 55,136 110,132 165,126 220,119 275,114 330,107 385,101 440,94 495,86 550,78 600,70"/><polyline className="chart-line tests-line" points="0,147 55,144 110,140 165,136 220,132 275,128 330,123 385,118 440,113 495,108 550,101 600,95"/></svg></div><footer><small>Jul 23&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jul 27&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jul 31&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aug 04&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aug 08&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aug 12&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aug 16&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aug 20</small></footer></article>
      <article className="reference-panel health-reference"><header><h2>System Health</h2><Link href="/admin/dashboard">View Details →</Link></header>{healthItems.map(([item, status]) => <div className="reference-health-row" key={item}><span>▣ &nbsp; {item}</span><b className={status !== 'Operational' ? 'health-not-configured' : ''}>{status}</b></div>)}<div className="reference-health-summary">✓ <strong>{databaseReady ? 'Core systems are available' : 'Database checks need attention'}</strong><small>Live status from current application checks</small></div></article>
      <article className="reference-panel activity-reference"><header><h2>Recent Activity</h2><Link href="/admin/users">View All</Link></header>{activity.data?.length ? activity.data.map(user => <div className="reference-activity-row" key={user.id}><span>♙</span><div><strong>New user registered</strong><small>{user.full_name || 'Unnamed user'}</small></div><time>{new Date(user.created_at).toLocaleDateString('en-IN')}</time></div>) : <div className="reference-empty">No recent activity yet.</div>}</article>
    </section>
    <section className="admin-lower-reference">
      <article className="reference-panel scraper-reference"><header><h2>Job Scraper Status</h2><Link href="/admin/jobs">View All →</Link></header><div className="mini-table"><div className="mini-table-head"><span>Source</span><span>Jobs Today</span><span>Total Jobs</span><span>Success Rate</span><span>Status</span></div>{sourceRows.map(row => <div className="scraper-row" key={row.source}><span className={`scraper-source scraper-${row.source.toLowerCase().replaceAll(' ', '-')}`}><i aria-hidden="true">{row.source === 'LinkedIn' ? 'in' : row.source === 'Instagram Posts' ? '◎' : row.source === 'Company Sites' ? '▥' : row.source[0]}</i>{row.source}</span><span>{row.today.toLocaleString('en-IN')}</span><span>{row.total.toLocaleString('en-IN')}</span><span>—</span><b className={row.total ? '' : 'health-not-configured'}>{row.total ? 'Active' : 'No data'}</b></div>)}</div></article>
      <article className="reference-panel analytics-reference"><header><h2>User Analytics</h2><select defaultValue="7"><option value="7">Last 7 Days</option></select></header><div className="analytics-empty"><strong>{Number(users.count ?? 0).toLocaleString('en-IN')}</strong><span>Total Users</span><small>Analytics will appear as activity is recorded.</small></div></article>
      <article className="reference-panel features-reference"><header><h2>Popular Features</h2><select defaultValue="7"><option value="7">Last 7 Days</option></select></header>{['Jobs','Resume Builder','Mock Tests','AI Tools','Learning','Voice Talk Zone'].map(item => <div className="feature-row" key={item}><span>{item}</span><b>—</b></div>)}</article>
      <article className="reference-panel latest-reference"><header><h2>Latest Users</h2><Link href="/admin/users">View All →</Link></header>{activity.data?.length ? activity.data.slice(0, 4).map(user => <div className="latest-row" key={user.id}><span>♙</span><strong>{user.full_name || 'Unnamed user'}</strong><small>{new Date(user.created_at).toLocaleDateString('en-IN')}</small><b>Active</b></div>) : <div className="reference-empty">No users yet.</div>}</article>
      <article className="reference-panel content-reference"><header><h2>Content Analytics</h2><select defaultValue="30"><option value="30">Last 30 Days</option></select></header><div className="content-stats"><div><span>¤</span><small>Resumes Created</small><strong>—</strong></div><div><span>✓</span><small>Tests Completed</small><strong>{tests.count ?? 0}</strong></div><div><span>◆</span><small>Courses Enrolled</small><strong>{learning.count ?? 0}</strong></div><div><span>✦</span><small>AI Queries</small><strong>—</strong></div></div></article>
      <article className="reference-panel actions-reference"><header><h2>Quick Actions</h2></header><div className="quick-actions"><Link href="/admin/jobs">♧ Add Job Source</Link><Link href="/admin/users">♙ Manage Users</Link><Link href="/admin/jobs">⚙ Monitor Scrapers</Link><Link href="/settings">⚯ Update Content</Link><Link href="/settings">⚙ System Settings</Link><Link href="/admin/dashboard">▥ View Reports</Link></div></article>
    </section>
  </div></Shell>;
}
