'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '../../../lib/supabase/client';

type Job = { id: string; title: string; company: string; location: string | null; description: string | null; skills: string[] | null; source: string | null; external_url?: string | null };

export default function JobDetail({ params }: { params: Promise<{ jobId: string }> }) {
  const [id, setId] = useState(''); const [job, setJob] = useState<Job | null>(null); const [form, setForm] = useState({ name: '', email: '', phone: '', cover: '' }); const [sent, setSent] = useState(false); const [gate, setGate] = useState(false); const [error, setError] = useState('');
  useEffect(() => { params.then(({ jobId }) => { setId(jobId); const saved = sessionStorage.getItem(`application:${jobId}`); if (saved) setForm(JSON.parse(saved)); createClient().from('jobs').select('*').eq('id', jobId).maybeSingle().then(({ data }) => setJob(data)); }); }, [params]);
  if (!job) return <main className="public-page"><p>Loading opportunity…</p></main>;
  const external = (job.source || '').toLowerCase() === 'external' || Boolean(job.external_url);
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); sessionStorage.setItem(`application:${id}`, JSON.stringify(form)); const { data: { user } } = await createClient().auth.getUser(); if (!user) { setGate(true); return; } await saveApplication(user.id); }
  async function saveApplication(userId: string | null) { const { error: insertError } = await createClient().from('applications').insert({ user_id: userId, job_id: id, applicant_name: form.name, applicant_email: form.email, applicant_phone: form.phone, notes: form.cover, source: job?.source || 'internal', status: 'applied', applied_at: new Date().toISOString() }); if (insertError) setError(insertError.message); else { sessionStorage.removeItem(`application:${id}`); setSent(true); } }
  async function guestSubmit() { setGate(false); await saveApplication(null); }
  const authUrl = `/login?redirect=${encodeURIComponent(`/jobs/${id}`)}&action=apply`;
  return <main className="public-page"><header className="public-header"><Link href="/" className="public-brand">SoftwareChinnodu</Link><nav><Link href="/jobs">Jobs</Link><Link href="/login" className="public-login">Log in</Link></nav></header><section className="public-card"><span className="public-kicker">{job.source || 'SoftwareChinnodu'}</span><h1>{job.title}</h1><p>{job.company} · {job.location || 'Location available'}</p><p>{job.description || 'Explore this opportunity and take your next career step.'}</p><div className="job-tags">{(job.skills || []).map(skill => <span key={skill}>{skill}</span>)}</div>{sent ? <><h2>Application submitted successfully</h2><p>Want to track this application?</p><Link className="button" href="/register">Create a free account</Link> <Link className="button public-outline" href="/jobs">Continue browsing jobs</Link></> : external ? <><p>Save this opportunity to your account before continuing to the employer.</p><Link className="button" href={authUrl}>Log in to save and continue</Link></> : <form onSubmit={submit}><h2>Apply now</h2><input required placeholder="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><input placeholder="Phone" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/><textarea placeholder="Cover letter" value={form.cover} onChange={e => setForm({ ...form, cover: e.target.value })}/>{error && <p className="auth-error">{error}</p>}<button className="button">Submit application</button></form>}{gate && <div className="public-card"><h2>Save & track your application</h2><p>Create an account to track status and prepare for your interview. You can also continue without an account.</p><Link className="button" href={authUrl}>Login</Link> <Link className="button public-outline" href={`/register?redirect=${encodeURIComponent(`/jobs/${id}`)}`}>Create free account</Link> <button className="button public-outline" onClick={guestSubmit}>Continue without account</button></div>}</section></main>;
}
