'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { Shell } from '../../components/Shell';
import { PrepBanner } from '../../components/PrepBanner';
import { CompanyLogo } from '../../components/CompanyLogo';

function WelcomeMessage(){const [name,setName]=useState<string|null>(null);useEffect(()=>{const supabase=createClient();supabase.auth.getUser().then(({data})=>{const user=data.user;if(user)setName(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'there')});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{const user=session?.user;if(user)setName(user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'there');else setName(null)});return()=>subscription.unsubscribe()},[]);return <><h1 className="title">{name?`Welcome back, ${name}! 👋`:'Welcome to CareerAI! 👋'}</h1><p className="sub">{name?"Here's what's happening with your career journey today.":'Explore your AI-powered career journey and get started today.'}</p></>}
import { createClient } from '../../lib/supabase/client';

const actions = [['📍','Find Jobs','/jobs'],['📄','Resume Builder','/resume-builder'],['✓','Mock Tests','/mock-tests'],['🎙️','Voice Talk Zone','/voice-talk-zone'],['◉','AI Tools','/ai-tools'],['🎓','Learning Path','/learning']];
const jobs: [string,string,string,string,string[]][] = [['G','Software Engineer, Backend','Google • Bengaluru, India','95%',['Python','Django','PostgreSQL','AWS']],['M','Software Engineer','Microsoft • Hyderabad, India','92%',['C#','.NET','Azure','SQL']],['S','Backend Developer','Swiggy • Bengaluru, India','90%',['Java','Spring Boot','Kafka','Redis']],['a','Software Development Engineer','Amazon • Pune, India','88%',['Python','AWS','DynamoDB','System Design']]];

export default function Dashboard(){const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');function ask(e:FormEvent){e.preventDefault();if(question.trim())setAnswer('Thanks — CareerAI will help you plan your next career step.');setQuestion('')}return <Shell><div className="content">
<div className="title-row"><div><WelcomeMessage /></div></div>
<div className="grid kpis">{[['💼','Recommended Jobs','128','↑ 18 new today','/jobs'],['📄','Applications','24','6 in progress','/applications'],['▥','Interviews','05','Next: Tomorrow','/applications'],['🎯','Profile Match Score','85%','↑ 12% this week','/career-insights']].map(x=><Link href={x[4]} className="card kpi" key={x[1]}><span className="icon">{x[0]}</span><span className="stat-content"><span className="label">{x[1]}</span><span className="num">{x[2]}</span><span className="trend">{x[3]}</span></span></Link>)}</div>
<PrepBanner />
<div className="main-columns"><section className="card jobs-card"><h2 className="section-title">Top Job Recommendations for You <Link href="/jobs" className="link">View all</Link></h2>{jobs.map(x=><Link href="/jobs" className="job" key={x[1]}><div className="logo">{x[0]}</div><div><h3>{x[1]}</h3><div className="meta">{x[2]}</div><div className="tags">{x[4].map(t=><span className="tag" key={t}>{t}</span>)}</div></div><div className="match">{x[3]} Match<br/><span className="meta">2h ago　♡</span></div></Link>)}<Link href="/jobs" className="link-inline">View all jobs　→</Link></section>
<section className="card insights-card"><h2 className="section-title">Your Career Insights <Link href="/career-insights" className="link">View full report</Link></h2><div className="insight"><div className="score"><strong>85%</strong><small>Overall Score</small></div><div className="meters">{[['Skills Match','90%'],['Experience Match','80%'],['Education Match','75%'],['Profile Strength','85%']].map(x=><div className="meter" key={x[0]}>{x[0]} <span>{x[1]}</span><i><b style={{width:x[1]}}/></i></div>)}</div></div><div className="callout">★ <b>Strengths</b><div className="tags"><span className="tag">Python</span><span className="tag">Backend Development</span><span className="tag">Problem Solving</span><span className="tag">System Design</span></div></div><div className="callout improve">✹ <b>Areas to Improve</b><div className="tags"><span className="tag">Docker</span><span className="tag">Kubernetes</span><span className="tag">DevOps</span></div></div></section>
<aside className="right-rail"><div className="card"><h2 className="section-title">Profile Completeness <span className="tag right">90%</span></h2><div className="progress"><b/></div><div className="check">✅ Basic Information<br/>✅ Skills　›<br/>✅ Experience　›<br/>✅ Education　›<br/>✅ Resume　›</div><Link className="button button-block" href="/settings">Improve Profile</Link></div><div className="card"><h2 className="section-title">Quick Actions</h2><div className="grid quick">{actions.map(x=><Link href={x[2]} key={x[1]}><span>{x[0]}</span><br/>{x[1]}</Link>)}</div></div><div className="card learning-card"><h2 className="section-title">Learning Path</h2><p>Personalized learning paths to upskill and advance your career.</p><Link className="button" href="/learning">Start Learning　→</Link></div></aside></div>
<form className="card assistant" onSubmit={ask}><div className="assistant-icon">🔮</div><div><b>Ask CareerAI Assistant</b><br/><span className="meta">Get answers, career advice, job suggestions & more...</span></div><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about your career..."/><button className="button">Ask　➤</button>{answer&&<p className="assistant-answer">{answer}</p>}</form>
</div></Shell>}
