'use client';
import { useState } from 'react';

type Item = { id: string; caption: string | null; permalink: string | null; media_type: string | null; media_url: string | null; thumbnail_url: string | null; posted_at: string | null; status: string };
export default function InstagramReview({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function importPosts() { setBusy(true); setMessage(''); const response = await fetch('/api/admin/instagram/import', { method: 'POST' }); const result = await response.json(); setMessage(response.ok ? `Imported ${result.imported} post(s). Refresh to review them.` : result.error); setBusy(false); }
  async function publish(id: string) { setBusy(true); const response = await fetch('/api/admin/instagram/publish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); const result = await response.json(); if (response.ok) setItems(items.map(item => item.id === id ? { ...item, status: 'approved' } : item)); else setMessage(result.error); setBusy(false); }
  return <section className="admin-panel-pro"><div className="panel-heading"><div><small>PENDING REVIEW</small><h2>{items.length} imported posts</h2></div><button className="admin-primary-action" onClick={importPosts} disabled={busy}>{busy ? 'Working…' : 'Import Instagram Posts'}</button></div>{message && <p className="admin-empty">{message}</p>}{items.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Post</th><th>Type</th><th>Posted</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{(item.caption || 'Untitled post').split('\n')[0].slice(0, 80)}</strong>{item.permalink && <><br/><a href={item.permalink} target="_blank" rel="noreferrer">Open Instagram post</a></>}</td><td>{item.media_type || 'Post'}</td><td>{item.posted_at ? new Date(item.posted_at).toLocaleDateString('en-IN') : '—'}</td><td><span className="status-chip">{item.status}</span></td><td>{item.status === 'pending' ? <button className="button" onClick={() => publish(item.id)} disabled={busy}>Publish job</button> : 'Published'}</td></tr>)}</tbody></table></div> : <div className="admin-empty">No Instagram posts imported yet.</div>}</section>;
}
