'use client';
import Link from 'next/link';
import { useState } from 'react';

type Extracted = { title?: string; company?: string; location?: string; jobId?: string; workMode?: string; category?: string };
type Item = { id: string; caption: string | null; permalink: string | null; media_type: string | null; posted_at: string | null; status: string; extracted_data?: Extracted | null };

export default function InstagramReview({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const pending = items.filter(item => item.status === 'pending');
  async function importPosts() { setBusy(true); const response = await fetch('/api/admin/instagram/import', { method: 'POST' }); const result = await response.json(); setMessage(response.ok ? `Imported ${result.imported} post(s). Refresh to review them.` : result.error); setBusy(false); }
  async function publish(id: string) { const response = await fetch('/api/admin/instagram/publish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Could not publish job.'); setItems(current => current.map(item => item.id === id ? { ...item, status: 'approved' } : item)); }
  async function publishSelected() { setBusy(true); setMessage(''); try { for (const id of selected) await publish(id); setSelected([]); setMessage('Selected jobs published successfully.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not publish selected jobs.'); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm('Delete this imported job draft?')) return; setBusy(true); const response = await fetch('/api/admin/instagram/delete', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); if (response.ok) { setItems(current => current.filter(item => item.id !== id)); setSelected(current => current.filter(value => value !== id)); } else setMessage((await response.json()).error); setBusy(false); }
  const allSelected = pending.length > 0 && pending.every(item => selected.includes(item.id));
  return <section className="admin-panel-pro instagram-review-panel"><div className="panel-heading"><div><small>INSTAGRAM IMPORTS</small><h2>{items.length} job drafts</h2></div><button className="admin-primary-action" onClick={importPosts} disabled={busy}>{busy ? 'Working…' : '+ Import Instagram Posts'}</button></div><div className="instagram-filters"><Link className="active" href="/admin/instagram">All ({items.length})</Link><Link href="#pending">Pending Review ({pending.length})</Link><Link href="#approved">Approved ({items.filter(item => item.status === 'approved').length})</Link><Link href="#rejected">Rejected ({items.filter(item => item.status === 'rejected').length})</Link><input placeholder="Search by company, job ID, or text..."/></div><div className="instagram-bulk-bar"><strong>Bulk Actions</strong><label><input type="checkbox" checked={allSelected} onChange={event => setSelected(event.target.checked ? pending.map(item => item.id) : [])}/> Select all</label><button onClick={publishSelected} disabled={busy || selected.length === 0}>Bulk Publish ({selected.length})</button><button onClick={() => selected.forEach(remove)} disabled={busy || selected.length === 0}>Bulk Delete</button></div>{message && <p className="admin-empty">{message}</p>}{items.length ? <div className="instagram-job-list"><div className="instagram-job-list-head instagram-job-list-head-wide"><span>Select</span><span>Role</span><span>Company</span><span>Location</span><span>Posted</span><span>Status</span><span>Actions</span></div>{items.map(item => { const details = item.extracted_data ?? {}; const secondary = details.workMode || details.category || ''; return <div className="instagram-job-list-row instagram-job-list-row-wide" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={item.status !== 'pending'} onChange={event => setSelected(current => event.target.checked ? [...current, item.id] : current.filter(id => id !== item.id))}/><div><strong>{details.title || (item.caption || 'Untitled job post').split('\n')[0].slice(0, 90)}</strong>{secondary && <small>{secondary}</small>}</div><span>{details.company || '—'}</span><span>{details.location || '—'}</span><span>{item.posted_at ? new Date(item.posted_at).toLocaleDateString('en-IN') : '—'}</span><span className="status-chip">{item.status}</span><div className="list-actions"><Link href={`/admin/instagram/${item.id}`}>Edit</Link>{item.status === 'pending' && <button onClick={() => remove(item.id)} disabled={busy}>Delete</button>}{item.status === 'pending' && <button className="publish-link" onClick={() => publish(item.id)} disabled={busy}>Publish</button>}</div></div>; })}</div> : <div className="admin-empty">No Instagram posts imported yet.</div>}</section>;
}
