'use client';
import { useState } from 'react';

type Item = { id: string; caption: string | null; permalink: string | null; media_type: string | null; media_url: string | null; thumbnail_url: string | null; posted_at: string | null; status: string };
export default function InstagramReview({ initialItems }: { initialItems: Item[] }) {
  const [items, setItems] = useState(initialItems); const [editing, setEditing] = useState<string | null>(null); const [drafts, setDrafts] = useState<Record<string, { title: string; company: string; location: string; salary: string; description: string; skills: string; external_url: string }>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function importPosts() { setBusy(true); setMessage(''); const response = await fetch('/api/admin/instagram/import', { method: 'POST' }); const result = await response.json(); setMessage(response.ok ? `Imported ${result.imported} post(s). Refresh to review them.` : result.error); setBusy(false); }
  async function publish(id: string) { setBusy(true); const response = await fetch('/api/admin/instagram/publish', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, job: drafts[id] }) }); const result = await response.json(); if (response.ok) setItems(items.map(item => item.id === id ? { ...item, status: 'approved' } : item)); else setMessage(result.error); setBusy(false); }
  function startEdit(item: Item) { setEditing(item.id); setDrafts({ ...drafts, [item.id]: { title: (item.caption || '').split('\n')[0] || 'Job opportunity', company: '', location: '', salary: '', description: item.caption || '', skills: '', external_url: item.permalink || '' } }); }
  return <section className="admin-panel-pro"><div className="panel-heading"><div><small>PENDING REVIEW</small><h2>{items.length} job drafts</h2></div><button className="admin-primary-action" onClick={importPosts} disabled={busy}>{busy ? 'Working…' : 'Import Instagram Posts'}</button></div>{message && <p className="admin-empty">{message}</p>}{items.length ? <div className="instagram-job-drafts">{items.map(item => <article className="instagram-job-draft" key={item.id}>{editing === item.id ? <div className="job-edit-form">{(['title','company','location','salary','skills','external_url'] as const).map(field => <label key={field}>{field.replace('_', ' ')}<input value={drafts[item.id]?.[field] || ''} onChange={event => setDrafts({ ...drafts, [item.id]: { ...drafts[item.id], [field]: event.target.value } })}/></label>)}<label className="wide">description<textarea value={drafts[item.id]?.description || ''} onChange={event => setDrafts({ ...drafts, [item.id]: { ...drafts[item.id], description: event.target.value } })}/></label><div className="draft-actions"><button className="button" onClick={() => publish(item.id)} disabled={busy}>Publish job</button><button className="admin-secondary-action" onClick={() => setEditing(null)}>Cancel</button></div></div> : <><div><small>INSTAGRAM {item.media_type || 'POST'} · {item.posted_at ? new Date(item.posted_at).toLocaleDateString('en-IN') : 'Recent'}</small><h3>{(item.caption || 'Untitled job post').split('\n')[0].slice(0, 100)}</h3><p>{item.caption || 'No caption available.'}</p></div><div className="draft-actions">{item.permalink && <a href={item.permalink} target="_blank" rel="noreferrer">View source</a>}{item.status === 'pending' && <button className="button" onClick={() => startEdit(item)}>Edit &amp; review</button>}{item.status === 'approved' && <span className="status-chip">Published</span>}</div></>}</article>)}</div> : <div className="admin-empty">No Instagram posts imported yet.</div>}</section>;
}
